export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'
export const LOAD_ALL_POSTS_SUCCESS = 'LOAD_ALL_POSTS_SUCCESS'
export const LOAD_POSTS_BY_CATEGORY_SUCCESS = 'LOAD_POSTS_BY_CATEGORY_SUCCESS'